name: 'Terraform Reusable CD workflow'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      bucket:
        required: true
      key:
        required: true
      region:
        required: true

permissions:
  contents: read

jobs:
  Plan-And-Apply-Terraform:
    name: 'Terraform Plan & Apply on ${{ inputs.environment }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.1"
      
      - name: Terraform Init
        working-directory: ${{ inputs.environment }}
        run: |
         terraform init -backend-config="bucket=${{ secrets.bucket }}" \
         -backend-config="key=${{ secrets.key }}" \
         -backend-config="region=${{ secrets.region }}"
        

      - name: Terraform Plan
        working-directory: ${{ inputs.environment }}
        run: |
          terraform plan -input=false -out=tf.out
          
       