name: 'Terraform CD'

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master

jobs:
  # Run-CI:
  #   uses: ./.github/workflows/terraform-reusable-ci.yaml
    
  Run-CD-Stage:
    # needs: Run-CI
    uses: ./.github/workflows/terraform-reusable-cd.yaml
    with:
      environment: stage
    secrets:
      bucket: ${{ secrets.bucket }}
      key: ${{ secrets.key }}
      region: ${{ secrets.region }}
      aws_iam_role_arn: ${{ secrets.aws_iam_role_arn }}

  # Run-CD-Prod:
  #   needs: Run-CI
  #   uses: ./.github/workflows/terraform-reusable-cd.yaml
  #   with:
  #     environment: prod
  #   secrets:
  #     bucket: ${{ secrets.bucket }}
  #     key: ${{ secrets.key }}
  #     region: ${{ secrets.region }}
  #     aws_iam_role_arn: ${{ secrets.aws_iam_role_arn }}
    