name: 'Terraform Plan'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  Setup-Terraform:
    name: 'Setup-Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.8.1"

    - name: Terraform Format
      run: terraform fmt --list=true -recursive -check
    
    - name: Terraform Validate Stage
      working-directory: ./stage  
      run: |
        terraform init -backend=false
        terraform validate

    - name: Terraform Validate Prod
      working-directory: ./prod  
      run: |
        terraform init -backend=false
        terraform validate
    
